---
title       : Analysis of the mtcars dataset
subtitle    : 
author      : Dipendra Kusi
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
github: 
        user: dipitak
        repo: shinyapp
---

## Coursera Shiny project Pitch
Here we have shown the relation between the HP varible with other varible so that relation between other variable can be explored.
Also through use of regression, we can predict the value of HP at different level. People can view the relation and regression curver by checking
the varible type through dropdown box.

## Data Source: mtcars dataset

> The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).

### Source
> Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.

---

## Summary of mtcars Data
```{r}
library(datasets)
head(mtcars, 2)
summary(mtcars)
```

---

## mtcars dataset - Format

**A data frame with 32 observations on 11 variables.**

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

---

## Analysis: ui code
```r
titlePanel("The relationship between variables and miles per horsepower (hp)"),
sidebarLayout(
sidebarPanel(
selectInput("variable", "Variable:",
    c("Number of cylinders" = "cyl",
      "Displacement (cu.in.)" = "disp",
      "Rear axle ratio" = "drat",
      "Weight (lb/1000)" = "wt",
      "1/4 mile time" = "qsec",
      "V/S" = "vs",
      "Transmission" = "am",
      "Number of forward gears" = "gear",
      "Number of carburetors" = "carb"
    ))


)
```
---

---
## Analysis - main code

```r
 
  formulaText <- reactive({
    paste("hp ~", input$variable)
  })
  
  formulaTextPoint <- reactive({
    paste("hp ~", "as.integer(", input$variable, ")")
  })
  
...
output$fit <- renderPrint({
        summary(fit()) 
})

output$hpPlot <- renderPlot({
    with(hpData, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })
})

```
---


